build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - command: ./vender/.bin/phpunit --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: php-clover
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests: true
filter:
  excluded_paths:
    - 'tests/*'
    - 'bin/*'
  paths:
    - "src/*"
checks:
  php: true
coding_style:
  php: {  }
